### ISSUE TITLE
Automatic generation of start page

### ISSUE THREAD

**Issue by plainionist** [plainionist/Plainion.DrawVista#1]
The start page (the SVG called "index") currently needs to be hand crafted. But actually it could be generated automatically by the system by creating a graph

- showing a "node" for each page existing in the system
- showing a directed edge from each page (node) to those pages (nodes) mentioned within this page

![Sample](https://github.com/plainionist/Plainion.DrawVista/assets/11823856/87c3353a-1a27-4359-862f-4458cd759ef0)

**Comment by wanderzirkus** [comment]
Implemented with https://github.com/plainionist/Plainion.DrawVista/commit/d5c0d3ce9621c3573b85e1a3a61bb4013d7740ae
